# Generated by Django 2.0 on 2018-04-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transactions',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
