# Generated by Django 2.0 on 2018-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0002_auto_20180410_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='paytm_number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
